### ISSUE TITLE
離床判定試験

### ISSUE THREAD

**Issue by ztacti** [core-rocket/Piglet#2]
離床判定試験のあれこれ

**Comment by ztacti** [comment]
３G？、フライトピン？

**Comment by onenechan** [comment]
3G and フライトピン(3Gだけでいい気もしてる)

**Comment by ztacti** [comment]
@onenechan 審査書初めて書いたので、わからないのですが、審査書に書いてあることって2次で変えても大丈夫なんですかね、、、できるできないは別として、機構だけでも搭載させた方がいいような気がしています。💦

**Comment by onenechan** [comment]
そうだね．2次までならいい気はしてるけど，機構だけは載せたほうがいいね．
そしてごめん両方使うなら or です

**Comment by ztacti** [comment]
プログラム完成。あとはやるのみ。
