### ISSUE TITLE
TWE-LITEの通信実験

### ISSUE THREAD

**Issue by ztacti** [core-rocket/Piglet#3]
TWE-LITEの通信実験のあれこれ

**Comment by ztacti** [comment]
TWEの通信できた。何メートル届くかはわからない。中継器の設置も技術的に可能

**Comment by ztacti** [comment]
STMF303K8との連携はまだやってない。これによってロガーの配線が変わるので最優先事項

**Comment by ztacti** [comment]
Serialできた。ダウンリンクはできるけど、TWEの公式ファームウェアをそのまま使っている感じです。

**Comment by onenechan** [comment]
twe無線試験やる？
