### ISSUE TITLE
ES920通信実験

### ISSUE THREAD

**Issue by ztacti** [core-rocket/Piglet#4]
ES920通信実験のあれこれ

**Comment by onenechan** [comment]
審査書に関してはどんぶらこの試験結果を使わせてもらおうと思っている

**Comment by ztacti** [comment]
@onenechan 資料をもし持っていたら共有していただけると嬉しいです！🙏

**Comment by onenechan** [comment]
どんぶらこgithubの通信試験のとこにのってる！2.5km

**Comment by ztacti** [comment]
使えるようになったので、早くやりたいが音はスケジュール。結局28日になる予感
