### ISSUE TITLE
ロガー制作

### ISSUE THREAD

**Issue by ztacti** [core-rocket/Piglet#5]
ロガー制作のあれこれ

**Comment by ztacti** [comment]
進捗まとめ
・ライブラリ作成9割完了
・単体での動作確認全て完了。
・ブレボ動作まだ
・基板設計まだ
・プログラム、地磁気とれん
・姿勢推定まだ
・バイナリデータまだ

**Comment by ztacti** [comment]
ライブラリ完了

**Comment by ztacti** [comment]
基板、バージョン１完成。
確認後、再設計

**Comment by onenechan** [comment]
ロガーの搭載位置どこにする？
機体班今固定方法決めてるからエンジン周りにするなら早めに言ったほうがいいかも！

**Comment by ztacti** [comment]
随分久々の更新。コードの進捗なし。
基板発注済み
頑張る
